;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        ))

(setq mc/cmds-to-run-once
      '(
        backward-delete-char
        keyboard-escape-quit
        mouse-secondary-save-then-kill
        mouse-set-region
        ))
