(require 'eshell)
(require 'em-hist)
(with-temp-buffer
  (eshell-mode)
  (insert "$ echo hello\n")
  (let ((marker (point-marker)))
    (set-marker-insertion-type marker t)
    (setq eshell-last-output-end marker))
  (insert "hello\n$ ")
  (goto-char (point-min))
  (message "Point at min: %s" (eshell-beginning-of-input))
  (goto-char (point-max))
  (message "Point at max: %s" (eshell-beginning-of-input))
  (message "Marker eshell-last-output-end: %s" eshell-last-output-end)
  )
